image:
  path: img/img1.png
  scale: 0.25

tray:
  name: qvga_7x7
  scale: 8

calibration_detector:
  preprocessing:
    block_radius: 50
    c: 20
  pattern:
    path: img/calibration_320.png
    scale: 0.25
  detector:
    match_threshold: 0.5
    clustering_bandwidth: 40

sensor_detectors:
- name: sensor_without_lid
  pattern:
    path: img/pattern1.png
    scale: 1
  detector:
    match_threshold: 0.3
- name: sensor_with_lid
  pattern:
    path: img/pattern2.png
    scale: 1
  detector:
    match_threshold: 0.5

